config/routes.rb
FlashDeals::Application.routes.draw do

  post "alerts/create"

  post "alerts/delete"

  get "user/signup"  # this is generated by rails
  post "user/signup" => "user#create"
  post "user/signin" # this is equivalent to the following?
  get "/user/signin"
  get "user/signout" 

  get 'catalogs/:catalog_id' => 'Show#show'
  get 'merchants/:merchant_id' => 'Show#show'
  get 'show/search' => 'show#show'
  get 'catalogs' => 'Show#list_catalogs'
  get 'merchants' => 'Show#list_merchants'
  post 'coupons/submit_deal(.:format)' => 'Coupons#submit_deal'
  post 'coupons/delete_deal(.:format)' => 'Coupons#delete_deal'
  get 'coupons/submit_deal(.:format)' => 'Coupons#submit_deal'
  root to: 'Show#show'

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @products = Product.order('percentage_saved DESC').page(params[:page]).per(5)
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<h1>Deals &amp; Coupons 
					
								 	for "Amazon"
								</h1>	
	<div id="content">
			<div id="contentLeft">
							<div class="leftSectionHead">
				<div><img border="0" src="http://dealsoutlet.net/media/logo/category_tab_l.png"/></div>
				<div class="leftSectionTitle">
					<div class="sectionTitleText">Hot Catalog</div>
				</div>
				<div><img border="0" src="http://dealsoutlet.net/media/logo/category_tab_r.png"/></div>
			</div>
			<div class="leftSectionBodyContainer">
			  <div class="leftSectionBody">
<ul>
<% @catalogs.each do |catalog| %>
	<li><a href=<%= catalog_path(catalog) %>><%= catalog.name %></li>
<% end %>
</ul>			


			<div class="listCatalog"><a href="http://dealsoutlet.net/show/list-catalog">List Catalogs...</a></div>			  </div>
			</div>
			
			<div class="horizontalSpace20">&nbsp;</div>
			
			<div class="leftSectionHead">
				<div><img border="0" src="http://dealsoutlet.net/media/logo/category_tab_l.png"/></div>
				<div class="leftSectionTitle">
					<div class="sectionTitleText">Hot Merchant</div>
				</div>
				<div><img border="0" src="http://dealsoutlet.net/media/logo/category_tab_r.png"/></div>
			</div>
			<div class="leftSectionBodyContainer">
			  <div class="leftSectionBody">

<ul>
<% @merchants.each do |merchant| %>
	<li><a href="<%= merchant.url %>"><%= merchant.name %></a></li>
<% end %>
</ul>			



			<div class="listCatalog"><a href="http://dealsoutlet.net/show/list-merchant">List Merchants...</a></div>			
			  </div>
			</div>

			<div class="horizontalSpace20">&nbsp;</div>

			</div>
			
			<div class="verticalSpace20">&nbsp;</div>
			
			<div id="contentCenter"> 
				<div class="centerSectionHead">
				</div> 
											<div class="dealList"><p class="moreDeals">
							  <a href="http://dealsoutlet.net/show/deal/plink/1344852" target="_blank" rel="nofollow"><strong>Shop "Amazon" Now</strong></a></p></div><div class="space"></div>

<% @products.each do |product| %>
<div class="dealList">
    <span class="productListImage">
	<a href=<%= product.detail_page_url %> target="_blank" rel="nofollow">
	<img border="0" src= <%= product.small_image_url %> />
        </a>
    </span>
<span>
    <table class="product">
        <tbody>
	    <tr>
		<td colspan=2>
			<b class="productListName">
				<a href=<%= product.detail_page_url %>  target="_blank" rel="nofollow"><%= product.title %></a>
			</b>
		</td>
            </tr>
  	    <tr>
		<td class="priceLabel">List Price:</td>
		<td class="listPrice">$<%= product.list_price/100.0 %></td>
	    </tr>
	    <tr>
		<td class="priceLabel">Price:</td>
		<td><b class="salePrice">$<%= product.price/100.0 %></b></td>
	    </tr>
	    <tr>
		<td class="priceLabel">You Save:</td>
	   	<td class="savePrice">$<%= (product.list_price - product.price)/100.0 %> (<%= product.percentage_saved %>%)</td>
	    </tr>
	</tbody>
    </table>
</span>
<p class="moreDeals">&nbsp;</p>
</div>
<% end %>
</div>
			<div class="verticalSpace20">&nbsp;</div>
        			<div id="contentRight">
									<div class="signupboxTopHorizontal">
				<div><img border="0" src="http://dealsoutlet.net/media/logo/signupbox_top_l.png"/></div>
				<div id="signupboxTop">Setup Deals Alerts
				</div>
				<div><img border="0" src="http://dealsoutlet.net/media/logo/signupbox_top_r.png"/></div>
			</div>
			<div class="signupboxContainer">
			  <div id="signupboxBody">
			    <form action="/member/login" method="post">
			  	<div class="signinText">Username:</div>
			  	<div><input class="signinInput" name="username" type="text"/></div>
			  	<div class="signinText">Password:</div>
			  	<div><input class="signinInput" name="password" type="password"/></div>
			  	<div id="signinButtons">
			  	<input id="signinButton" type="submit" value="Signin!"/>
			  	<a href="http://dealsoutlet.net/member/register"><input id="signupButton" type="button" value="Signup!"/></a>
				<input type="hidden" name="check" value="1"/>
			  	</form>
			  	</div>
			  </div>
			</div>
			
			<div class="signupboxHorizontal">
				<div><img border="0" src="http://dealsoutlet.net/media/logo/signupbox_bottom_l.png"/></div>
				<div id="signupboxBottom"></div>
				<div><img border="0" src="http://dealsoutlet.net/media/logo/signupbox_bottom_r.png"/></div>
			</div>
					
			<div class="horizontalSpace20">&nbsp;</div>

			<div class="rightSectionHead">
				<div><img border="0" src="http://dealsoutlet.net/media/logo/category_tab_l.png"/></div>
				<div class="rightSectionTitle">
					<div class="sectionTitleText">Travel</div>
				</div>
				<div><img border="0" src="http://dealsoutlet.net/media/logo/category_tab_r.png"/></div>
			</div>

			<div class="rightSectionBodyContainer">
		        <div class="rightSectionBody">
			<ul>
				<% @travel_sites.each do |site| %>
				<li> <a href="<%= site.url %>"><%= site.name %></li>
				<% end %>
			</ul>
			<div class="listCatalog"><a href="http://dealsoutlet.net/show/deal/catalog/177/name/Travel+%26+Vacation">List All...</a></div>
			  </div>
			</div>

			<div class="horizontalSpace20">&nbsp;</div>
					

			<div class="rightSectionHead">
				<div><img border="0" src="http://dealsoutlet.net/media/logo/category_tab_l.png"/></div>
				<div class="rightSectionTitle">
					<div class="sectionTitleText">Submit a Deal</div>
				</div>
				<div><img border="0" src="http://dealsoutlet.net/media/logo/category_tab_r.png"/></div>
			</div>

			<div class="rightSectionBodyContainer">
			  <div class="rightSectionBody">
			  	<div id="submitDealReturnText"></div>
				<textarea id="submitDeal" cols="20" rows="3" name="submitDeal"></textarea>				
				<input type="button" value="Submit" onclick="submitDeal()"/>
			  </div>
			</div>
			<div class="horizontalSpace20">&nbsp;</div>



						</div>
		</div>