config/routes.rb
FlashDeals::Application.routes.draw do

  post "alerts/create"

  post "alerts/delete"

  get "user/signup"  # this is generated by rails
  post "user/signup" => "user#create"
  post "user/signin" # this is equivalent to the following?
  get "/user/signin"
  get "user/signout" 

  get 'catalogs/:catalog_id' => 'Show#show'
  get 'merchants/:merchant_id' => 'Show#show'
  get 'show/search' => 'show#show'
  get 'catalogs' => 'Show#list_catalogs'
  get 'merchants' => 'Show#list_merchants'
  post 'coupons/submit_deal(.:format)' => 'Coupons#submit_deal'
  post 'coupons/delete_deal(.:format)' => 'Coupons#delete_deal'
  get 'coupons/submit_deal(.:format)' => 'Coupons#submit_deal'
  root to: 'Show#show'

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  has_many :products
  attr_accessible :name, :url, :browse_node_id
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  # GET /catalogs
  # GET /catalogs.json
  def index
    @catalogs = Catalog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @catalogs }
    end
  end

  # GET /catalogs/1
  # GET /catalogs/1.json
  def show
    @catalog = Catalog.find(params[:id])
    @products = Product.where(catalog_id: params[:id]).order('percentage_saved DESC').page(params[:page]).per(5)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @catalog }
    end
  end

  # GET /catalogs/new
  # GET /catalogs/new.json
  def new
    @catalog = Catalog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @catalog }
    end
  end

  # GET /catalogs/1/edit
  def edit
    @catalog = Catalog.find(params[:id])
  end

  # POST /catalogs
  # POST /catalogs.json
  def create
    @catalog = Catalog.new(params[:catalog])

    respond_to do |format|
      if @catalog.save
        format.html { redirect_to @catalog, notice: 'Catalog was successfully created.' }
        format.json { render json: @catalog, status: :created, location: @catalog }
      else
        format.html { render action: "new" }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /catalogs/1
  # PUT /catalogs/1.json
  def update
    @catalog = Catalog.find(params[:id])

    respond_to do |format|
      if @catalog.update_attributes(params[:catalog])
        format.html { redirect_to @catalog, notice: 'Catalog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogs/1
  # DELETE /catalogs/1.json
  def destroy
    @catalog = Catalog.find(params[:id])
    @catalog.destroy

    respond_to do |format|
      format.html { redirect_to catalogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/views/catalogs/_form.html.erb
<%= form_for(@catalog) do |f| %>
  <% if @catalog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@catalog.errors.count, "error") %> prohibited this catalog from being saved:</h2>

      <ul>
      <% @catalog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/catalogs/edit.html.erb
<h1>Editing catalog</h1>

<%= render 'form' %>

<%= link_to 'Show', @catalog %> |
<%= link_to 'Back', catalogs_path %>

app/views/catalogs/index.html.erb
<h1>Listing catalogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @catalogs.each do |catalog| %>
  <tr>
    <td><%= catalog.name %></td>
    <td><%= catalog.url %></td>
    <% if false %>
    <td><%= link_to 'Show', catalog %></td>
    <td><%= link_to 'Edit', edit_catalog_path(catalog) %></td>
    <td><%= link_to 'Destroy', catalog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/catalogs/new.html.erb
<h1>New catalog</h1>

<%= render 'form' %>

<%= link_to 'Back', catalogs_path %>